### **Basic of functions**

In [1]:
import numpy as np

In [2]:
arr = np.arange(1000)

In [3]:
pythlist = list(range(1000))

In [4]:
array1= np.array([[1,5,6,3,8],[2,9,1,6,8]])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(2, 5)

In [7]:
array1.dtype

dtype('int64')

In [8]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
array1*array1

array([[ 1, 25, 36,  9, 64],
       [ 4, 81,  1, 36, 64]])

## ***Slicing***





In [12]:
array2 = np.array([5,4,6,3,3,3])

In [13]:
arr = array2[4:6].copy()

In [14]:
arr

array([3, 3])

In [15]:
arr[0]=7

In [16]:
array2

array([5, 4, 6, 3, 3, 3])