In [1]:
import numpy as np

In [2]:
a= np.array([[1,2,3],[4,5,6]])

In [4]:
a.sum(axis=0)

array([5, 7, 9])

In [5]:
b = np.array([[7,8,9],[2,8,0]])

In [6]:
a.dot(b.transpose())

array([[ 50,  18],
       [122,  48]])

In [8]:
np.dot(a,b.transpose())

array([[ 50,  18],
       [122,  48]])

In [9]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [13]:
a= np.array([[11,2,3],
             [4,15,6]])

In [14]:
np.sort(a)

array([[ 2,  3, 11],
       [ 4,  6, 15]])

In [15]:
np.sort(a, axis=0)

array([[ 4,  2,  3],
       [11, 15,  6]])

In [21]:
a=np.array([1,5,65,3,5,3,89,48,5,2,54,1,68,4,6,49,8,6,54,64,])
a.reshape(5,4)

array([[ 1,  5, 65,  3],
       [ 5,  3, 89, 48],
       [ 5,  2, 54,  1],
       [68,  4,  6, 49],
       [ 8,  6, 54, 64]])

In [22]:
np.argsort(a)

array([ 0, 11,  9,  3,  5, 13,  8,  1,  4, 14, 17, 16,  7, 15, 18, 10, 19,
        2, 12,  6])

In [23]:
np.argmin(a)

0

In [24]:
np.argmax(a)

6